### ISSUE TITLE
Usercontroller関連全般

### ISSUE THREAD

**Issue by Takafumi-Kondo** [hot-milk/nagano_record_online#83]
・adminで一覧からshowへいくとtopページへ遷移してしまう。(自身のマイページは問題なし
・admin側editページへはいけるがupdateでなぜかtopへ遷移してしまう(updateはされている)
・destroyでNameError in UsersController#destroy uninitialized constant User::Shipmentと出る

**Comment by neopuri0224** [comment]
~~adminで一覧からshowへいくとtopページへ遷移してしまう。(自身のマイページは問題なし
UserコントローラーのShowアクションに以下の記述が入っていた為削除しました。現在は問題なく動作しています。     
if current_user != @user
    redirect_to root_path
end

**Comment by neopuri0224** [comment]
・admin側editページへはいけるがupdateでなぜかtopへ遷移してしまう(updateはされている)
editアクションの記述を変更しました。動作確認できてます。

**Comment by neopuri0224** [comment]
・destroyでNameError in UsersController#destroy uninitialized constant User::Shipmentと出る
Shipmentテーブルを削除したのに、UserモデルにShipmentモデルとのアソシエーションが残っていたことが原因でした。解決済みです。
